name: Deploy main branch

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    environment:
      name: Production
    strategy:
      matrix:
        python-version:
          - 3.8
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - run: npm ci
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest moto boto3
        pip install moto[mock_dynamodb2]
        pip install coverage
    # Deployment of your project
    - name: Install Plugin and Deploy
      uses: serverless/github-action@v3.1
      with:
        args: -c "serverless plugin install --name serverless-python-requirements && serverless deploy --verbose"
        entrypoint: /bin/sh
      env:
        #SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
        # or if using AWS credentials directly
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Run tests
      run: pytest
    - name: Run tests coverage
      run: |
        coverage run -m pytest
        coverage report

