name: Deploy main branch

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    environment:
      name: Production
    strategy:
      matrix:
        python-version:
          - 3.8
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        node-version: ${{ matrix.python-version }}
    - run: npm ci
    # Deployment of your project
    - name: Serverless Deploy
      uses: sumeetweb/serverless-deploy@master
      with:
        args: ''  # any deploy arguments you want to pass
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

